### ISSUE TITLE
[Perf] 阿里云 ECS 服务器使用 EIP 时无法列举出来

### ISSUE THREAD

**Issue by AlienHub** [wgpsec/lc#15]
### 描述你希望优化的功能

建议支持使用 EIP 的场景。

**Comment by tarihub** [comment]
@AlienHub 师傅你好，写个功能直接枚举所有已分配 eip 能否满足需求？

**Comment by AlienHub** [comment]
> @AlienHub 师傅你好，写个功能直接枚举所有已分配 eip 能否满足需求？

当然可以，太好啦！

**Comment by teamssix** [comment]
感谢师傅提交的 Issue，已修复这个 Bug
